#----------------------------------------------------------------
# Makefile
# Aryan Samuel
# arsamuel
# CMPS 12B
# 03/31/16
# Lab 1
# The following is a Makefile for HelloUser & HelloUser2
#----------------------------------------------------------------

JAVASRC     = HelloUser.java HelloUser2.java
SOURCES     = README Makefile $(JAVASRC)
MAINCLASS   = HelloUser2
CLASSES     = HelloUser.class HelloUser2.class
JARFILE     = Hello
SUBMIT      = submit cmps012b-pt.s16 lab1

all: $(JARFILE)

$(JARFILE): $(CLASSES)
	echo Main-class: $(MAINCLASS) > Manifest
	jar cvfm $(JARFILE) Manifest $(CLASSES)
	rm Manifest
	chmod +x $(JARFILE)

$(CLASSES): $(JAVASRC)
	javac -Xlint $(JAVASRC)

clean:
	rm $(CLASSES) $(JARFILE)

submit: $(SOURCES)
	$(SUBMIT) $(SOURCES)

check:
	ls  /afs/cats.ucsc.edu/class/cmps012b-pt.s16/lab1/arsamuel
